sudo: required

arch: arm64

language: python

python:
  - "3.7"

install:
  - apt update && sudo apt upgrade
  - apt install libopenblas-dev libblas-dev m4 cmake cython python3-dev python3-yaml python3-setuptools
  - mkdir pytorch_install && cd pytorch_install
  - git clone --branch=1.4.0 --depth=1 --recursive https://github.com/pytorch/pytorch --branch=1.4.0
  - cd pytorch
  
script:
  - python3 setup.py build
