sudo: required

arch: arm64

language: python

python:
  - "3.7"

#addons:
#  apt:
#    update: true

before_install:
  - sudo apt-get -y install libopenblas-dev libblas-dev m4 cmake cython python3-dev python3-yaml python3-setuptools

before_script:
  - mkdir pytorch_install && cd pytorch_install
  - git clone --branch=v1.4.0 --depth=1 --recursive https://github.com/pytorch/pytorch
  - cd pytorch
  
script:
  - python3 setup.py build
