sudo: required

language: python

arch: arm64

python:
   - "3.7"
   
services:
  - docker
  - conda

before_install:
  - git clone https://github.com/pytorch/pytorch.git
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git pull
  - git checkout v1.4.0a0
  - git submodule update --init --recursive
  - cd pytorch

install:
  - pip install -r requirements.txt


script:
  - make -f docker.Makefile