sudo: required

arch: arm64

language: python

python:
  - "3.7"

#addons:
#  apt:
#    update: true

before_install:
  - sudo apt-get -y install libopenblas-dev libblas-dev m4 cmake cython python3-dev python3-yaml python3-setuptools

before_script:
  - mkdir pytorch_install && cd pytorch_install
  - git clone --branch=v1.4.0 --depth=1 --recursive https://github.com/pytorch/pytorch
  - cd pytorch
  - pip install pyyaml
  - export USE_CUDA=0
  - export USE_DISTRIBUTED=1
  - export USE_MKLDNN=0
  - export USE_NNPACK=1
  - export USE_QNNPACK=1
  - export TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" 
  - export TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
  
script:
  - python3 setup.py build
