sudo: required

arch: arm64

language: python

python:
  - "3.7"

#addons:
#  apt:
#    update: true

install:
  - sudo apt-get -y install libopenblas-dev libblas-dev m4 cmake cython python3-dev python3-yaml python3-setuptools python3-wheel python3-pillow python3-numpy

before_script:
  - mkdir pytorch_install && cd pytorch_install
  - git clone --branch=v1.4.0 --depth=1 --recursive https://github.com/pytorch/pytorch
  - cd pytorch
  - git submodule update --remote third_party/protobuf
  - export NO_CUDA=1
  - export NO_DISTRIBUTED=1
  - export NO_MKLDNN=1 
  - export NO_NNPACK=1
  - export NO_QNNPACK=1
  - pip install pyyaml
  
script:
  - python3 setup.py build
