sudo: required

arch: 
    - arm64
    - amd64
services:
  - docker

script:
  - docker build -t tyuio6914/pytorch:latest .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tyuio6914/pytorch:latest
